# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0002_auto_20170503_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
