# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0004_auto_20170503_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='название'),
        ),
    ]
