# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0006_auto_20170505_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
