# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0007_album_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
