# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0008_auto_20170512_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='data',
            new_name='date',
        ),
    ]
