# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0009_auto_20170512_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='inte',
            field=models.ImageField(default=8, upload_to=''),
        ),
    ]
