# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albome', '0011_remove_album_inte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['album'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
